on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: # This allows you to run it manually!

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping PythonAnywhere
        run: curl https://yourname.pythonanywhere.com/check
